### ISSUE TITLE
Brazil zones with DST have wrong TZOFFSETFROM

### ISSUE THREAD

**Issue by darktrojan** [benfortuna/tzurl#34]
For America/Sao_Paulo, America/Campo_Grande, and America/Cuiaba the TZOFFSETFROM is the same as TZOFFSETTO for the standard component, e.g.:

```
BEGIN:STANDARD
TZOFFSETFROM:-0300
TZOFFSETTO:-0300
TZNAME:-03
DTSTART:19700215T000000
```

**Comment by SirGlorg** [comment]
@benfortuna we seem to be hitting this issue. I assume this is the place to go for the root ical4j vcalendar definitions, right?

Brazil dropped their DST last year, however the vcalendar definitions seem to be old, and the recurrence rules in ical4j based on the vcalendar available at http://tzurl.sgp1.cdn.digitaloceanspaces.com/zoneinfo/America/Sao_Paulo.ics contain incorrect DST rules (should be none).

I couldn't find any reference on how to trigger re-computation of the vcalendar definition. Can you help us out on this? This is becoming a major issue for our produciton system, since we're implementing the ical in our scheduling service. The incorrect DST times for the whole Brazilian region is coming in 3 weeks. Can we have the definitions updated by then? Can I help with that?

**Comment by SirGlorg** [comment]
I checked out the `develop` branch, built and launched the docker image, and checked the resulting Sao Paulo ics definition. The file was identical to what I can see on the web (my previous comment). The output showed a bunch of warnings, but none related to the Sao Paulo zone.

**Comment by benfortuna** [comment]
I've just released a new ical4j version with updated timezone definitions, which make fix the issue. I'll try to add some tests to verify.

**Comment by SirGlorg** [comment]
Thank you Ben, this is much appreciated. The definition for the Sao Paulo looks better (checking the diff in the ical4j project optically). The 3.0.x ical4j updates the definitions from the tzurl.org by default. It's directed by the `net.fortuna.ical4j.timezone.update.enabled={true|false}` I believe. Do you have an estimate for the update of the tzurl.org, or would it be better for us to disable the auto-update, and use the definitions bundled with the ical4j? Is there a recommended approach?

**Comment by benfortuna** [comment]
I've now updated the definitions on tzurl.org, so feel free to use either approach.

I did change the default behaviour of ical4j to not update from tzurl.org, as there were some concerns about pulling data from Internet without explicit configuration.

**Comment by SirGlorg** [comment]
I can verify, that the timezone is now evaluated properly. Even from the tzurl.org with older ical4j library version. Awesome @benfortuna, thank you.

**Comment by benfortuna** [comment]
That's great, thanks for confirming.
